twig:
  file_name_pattern: '*.twig'
  globals:
    app_locale: '%app_locale%'
    app_settings: '@App\Service\SettingsService'
    app_quizzService: '@App\Service\QuizzService'

when@test:
  twig:
    strict_variables: true
